### ISSUE TITLE
Concurrent requests unsupported

### ISSUE THREAD

**Issue by AdrianLThomas** [samuelbr/OpenALPR-server#2]
If you make two requests at the same time, you get the following error response:
Premature end of JPEG file

**Comment by samuelbr** [comment]
Can you test image or scenario. I can't reproduce your issue. 
Thanks.

**Comment by AdrianLThomas** [comment]
Hi,

Yes I can repro this quite easily.

- Open a browser
- Put this in the url and hit enter: http://localhost:8080/?image_url=http://cdn2.autoexpress.co.uk/sites/autoexpressuk/files/2016/04/bmw_m4_gts_011.jpg&country_code=gb
- Press F5 a couple of times
- Response is as per original post.

Cheers,
Adrian

**Comment by samuelbr** [comment]
Thanks @AdrianLThomas

**Comment by AdrianLThomas** [comment]
Awesome. Thanks @samuelbr
